### ISSUE TITLE
Add support for python 3.10

### ISSUE THREAD

**Issue by pallxk** [Wiredcraft/pipelines#127]
Using the latest commit of pipelines

```
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/Wiredcraft/pipelines@f8f5692b99944bd67b8ef43a9c73fc548f216e3f
  Cloning https://github.com/Wiredcraft/pipelines (to revision f8f5692b99944bd67b8ef43a9c73fc548f216e3f) to /tmp/pip-req-build-gy140aca
  Running command git clone -q https://github.com/Wiredcraft/pipelines /tmp/pip-req-build-gy140aca
  Running command git rev-parse -q --verify 'sha^f8f5692b99944bd67b8ef43a9c73fc548f216e3f'
  Running command git fetch -q https://github.com/Wiredcraft/pipelines f8f5692b99944bd67b8ef43a9c73fc548f216e3f
Requirement already satisfied: certifi==2021.10.8 in /usr/lib/python3.10/site-packages (from pipelines==0.0.15) (2021.10.8)
Requirement already satisfied: docopt==0.6.2 in /usr/lib/python3.10/site-packages (from pipelines==0.0.15) (0.6.2)
Requirement already satisfied: dotmap==1.3.26 in ./lib/python3.10/site-packages (from pipelines==0.0.15) (1.3.26)
Requirement already satisfied: filelock==3.4.0 in ./lib/python3.10/site-packages (from pipelines==0.0.15) (3.4.0)
Requirement already satisfied: jinja2==3.0.3 in /usr/lib/python3.10/site-packages (from pipelines==0.0.15) (3.0.3)
Requirement already satisfied: pyyaml==6.0 in /usr/lib/python3.10/site-packages (from pipelines==0.0.15) (6.0)
Requirement already satisfied: requests==2.26.0 in ./lib/python3.10/site-packages (from pipelines==0.0.15) (2.26.0)
Requirement already satisfied: schema==0.7.5 in ./lib/python3.10/site-packages (from pipelines==0.0.15) (0.7.5)
Requirement already satisfied: sh==1.14.2 in ./lib/python3.10/site-packages (from pipelines==0.0.15) (1.14.2)
Requirement already satisfied: tornado==5.1.1 in ./lib/python3.10/site-packages (from pipelines==0.0.15) (5.1.1)
Requirement already satisfied: urllib3==1.26.9 in /usr/lib/python3.10/site-packages (from pipelines==0.0.15) (1.26.9)
Requirement already satisfied: charset-normalizer==2.0.12 in ./lib/python3.10/site-packages (from pipelines==0.0.15) (2.0.12)
Requirement already satisfied: idna==3.3 in /usr/lib/python3.10/site-packages (from pipelines==0.0.15) (3.3)
Requirement already satisfied: contextlib2==21.6.0 in ./lib/python3.10/site-packages (from pipelines==0.0.15) (21.6.0)
Requirement already satisfied: markupsafe==2.1.1 in /usr/lib/python3.10/site-packages (from pipelines==0.0.15) (2.1.1)
```

And python 3.10

```
$ python --version
Python 3.10.4
```

Currently it fails with the following error:

```
$ pipelines
Traceback (most recent call last):
  File "/home/lxk/.local/bin/pipelines", line 33, in <module>
    sys.exit(load_entry_point('pipelines==0.0.15', 'console_scripts', 'pipelines')())
  File "/home/lxk/.local/bin/pipelines", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lxk/.local/lib/python3.10/site-packages/pipelines/cli.py", line 32, in <module>
    from pipelines.api import server
  File "/home/lxk/.local/lib/python3.10/site-packages/pipelines/api/server.py", line 20, in <module>
    from tornado.web import (
  File "/home/lxk/.local/lib/python3.10/site-packages/tornado/web.py", line 88, in <module>
    from tornado import httputil
  File "/home/lxk/.local/lib/python3.10/site-packages/tornado/httputil.py", line 107, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by sp3c73r2038** [comment]
I think we could upgrade tornado to [6.1](ttps://github.com/tornadoweb/tornado/blob/v6.1.0/tornado/httputil.py#L76) which addressed this issue, thus support python >= 3.5.

**Comment by sp3c73r2038** [comment]
currently blocked by some legacy code. `return_future` is removed from tornado 6.0[1]. which is used by current code[2].

- https://www.tornadoweb.org/en/stable/releases/v6.0.0.html#tornado-concurrent
- https://github.com/Wiredcraft/pipelines/blob/master/pipelines/api/ghauth.py#L25
