### ISSUE TITLE
[BUG] Install of client fails

### ISSUE THREAD

**Issue by hunvreus** [Wiredcraft/pipelines#15]
This is the error I get when trying to install:

```
Berders-MacBook-2:app hunvreus$ npm install
npm WARN package.json getPipelines@2.0.0 Normalized value of bugs field is an empty object. Deleted.
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated cross-spawn-async@2.0.0: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> spawn-sync@1.0.15 postinstall /Users/hunvreus/Workspace/pipelines/app/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

-
> node-sass@3.4.2 install /Users/hunvreus/Workspace/pipelines/app/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/hunvreus/Workspace/pipelines/app/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@3.4.2 postinstall /Users/hunvreus/Workspace/pipelines/app/node_modules/node-sass
> node scripts/build.js

` /Users/hunvreus/Workspace/pipelines/app/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> fsevents@1.0.14 install /Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> getPipelines@2.0.0 postinstall /Users/hunvreus/Workspace/pipelines/app
> npm run dist


> getPipelines@2.0.0 dist /Users/hunvreus/Workspace/pipelines/app
> cross-env NODE_ENV=production webpack -p --progress

 95% emitfs.js:549          
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/hunvreus/Workspace/pipelines/app/index.tpl.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Compiler.<anonymous> (/Users/hunvreus/Workspace/pipelines/app/webpack.config.production.js:50:43)
    at Compiler.applyPlugins (/Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/node_modules/tapable/lib/Tapable.js:26:37)
    at Compiler.<anonymous> (/Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/lib/Compiler.js:193:12)
    at Compiler.emitRecords (/Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.next (/Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at /Users/hunvreus/Workspace/pipelines/app/node_modules/assets-webpack-plugin/index.js:78:9
    at /Users/hunvreus/Workspace/pipelines/app/node_modules/assets-webpack-plugin/lib/output/createQueuedWriter.js:15:7
    at /Users/hunvreus/Workspace/pipelines/app/node_modules/assets-webpack-plugin/lib/output/createOutputWriter.js:50:11
    at /Users/hunvreus/Workspace/pipelines/app/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! getPipelines@2.0.0 dist: `cross-env NODE_ENV=production webpack -p --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getPipelines@2.0.0 dist script 'cross-env NODE_ENV=production webpack -p --progress'.
npm ERR! This is most likely a problem with the getPipelines package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack -p --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs getPipelines
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls getPipelines
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hunvreus/Workspace/pipelines/app/npm-debug.log

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! getPipelines@2.0.0 postinstall: `npm run dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getPipelines@2.0.0 postinstall script 'npm run dist'.
npm ERR! This is most likely a problem with the getPipelines package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs getPipelines
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls getPipelines
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hunvreus/Workspace/pipelines/app/npm-debug.log
```

If our client is truly 100% separate from the backend, maybe we should move on with an http://electron.atom.io/ app to help DevOps folks move on with their days. This may mean as well separating the repos for the client and backend..? @JuhaS

**Comment by JuhaS** [comment]
The client build is not now required for deploying pipelines (it is pre-build by developers).
