### ISSUE TITLE
Pipelines crash when pipeline file is missing

### ISSUE THREAD

**Issue by zbal** [Wiredcraft/pipelines#51]
Typically when using links and the destination does not exist, pipeline will try to read the file and fail - crashing the app....

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 2800, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipelines/api/server.py", line 257, in get
    with open(os.path.join(workspace, path)) as f:
IOError: [Errno 2] No such file or directory: '/workspace/test.yml'
ERROR:tornado.access:500 GET /api/pipelines/ (172.17.0.1) 3.98ms
```

**Comment by zbal** [comment]
Fixed - closing.
