### ISSUE TITLE
GitHub auth fails with none lower() error

### ISSUE THREAD

**Issue by JonLundy** [Wiredcraft/pipelines#83]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1445, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/pipelines/api/ghauth.py", line 189, in get
    if filter(lambda x: x['slug'].lower() == team.lower() and x.get('organization',{}).get('name', '').lower() == org.lower(), teams):
  File "/usr/local/lib/python2.7/dist-packages/pipelines/api/ghauth.py", line 189, in <lambda>
    if filter(lambda x: x['slug'].lower() == team.lower() and x.get('organization',{}).get('name', '').lower() == org.lower(), teams):
AttributeError: 'NoneType' object has no attribute 'lower'

```

**Comment by JuhaS** [comment]
This seems to be a bug on cases where user is not part of a team, labelling accordingly.

**Comment by JonLundy** [comment]
@JuhaS do you have a suggestion on how to work around this bug? I am a member of the team that i specified with `--github-auth`. This just started happening out of nowhere for me. It was working at least a week ago.

**Comment by JonLundy** [comment]
I will just switch to user/pass for now. :|

**Comment by kaleocheng** [comment]
we did lots of updates recently, and this should be covered. closing as done. feel free to reopen it if still an issue
